name: "resnet50"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
  {
    name: "data"              # matches ONNX input
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "resnetv24_dense0_fwd"   # matches ONNX output
    data_type: TYPE_FP32
    dims: [1000]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
