MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="NODEADM-BOUNDARY"

--NODEADM-BOUNDARY
Content-Type: application/node.eks.aws

apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    name: ${cluster_name}
    apiServerEndpoint: ${cluster_endpoint}
    certificateAuthority: ${cluster_ca}
  kubelet:
    flags:
      - --node-labels=nvidia.com/gpu=true
    config:
      clusterDNS:
        - 10.100.0.10
  bootstrap:
    packages:
      - amazon-ssm-agent
    additionalSystemdUnits:
      - name: amazon-ssm-agent.service
        enable: true
        command: start

--NODEADM-BOUNDARY--
